project_id = "ppnunnmjvpiwrrrbluno"

[auth]
enable_signup = true

[functions.generate-pdf-document]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-welcome-email-idempotent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false